version: "3.9"
services:

  postgres:
    image: postgres:14-alpine
    hostname: postgres
    environment:
      - PGPORT=5432
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine
    command: --port 6380
    ports:
      - "6380:6380"
    healthcheck:
      test: [ "CMD", "redis-cli", "-p", "6380", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  vault:
    image: vault:latest
    volumes:
      - ~/.vault/policies:/vault/policies
      - ~/.vault/data:/vault/data
      - ~/.vault/file:/vault/file:rw
      - ~/.vault/plugins:/vault/plugins
      - ./config:/vault/config
      - ./scripts:/vault/scripts
    ports:
      - 8201:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
      - VAULT_ADDRESS=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: /vault/scripts/vault-init.sh

  platform:
    image: sh-id-platform/api:latest
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
      - vault
    environment:
      - SH_ID_PLATFORM_DATABASE_URL=postgres://polygonid:polygonid@postgres:5432/platformid?sslmode=disable
      - SH_ID_PLATFORM_KEY_STORE_ADDRESS=http://vault:8200
      - SH_ID_PLATFORM_KEY_STORE_TOKEN=${KEY_STORE_TOKEN}
      - SH_ID_PLATFORM_REDIS_URL=redis://@redis:6380/1
      - SH_ID_PLATFORM_ETHEREUM_URL=${KALEIDO_NODE_URL}
      - SH_ID_PLATFORM_ETHEREUM_CONTRACT_ADDRESS=${STATE_CONTRACT}
      - SH_ID_PLATFORM_SERVER_URL=http://localhost:3001
      # These environment vars overwrite the ones in config.toml
      #      - SH_ID_PLATFORM_SERVER_PORT=3001
      #      - SH_ID_PLATFORM_NATIVE_PROOF_GENERATION_ENABLED=true
      #      - SH_ID_PLATFORM_PUBLISH_KEY_PATH=pbkey
      #      - SH_ID_PLATFORM_ONCHAIN_PUBLISH_STATE_FRECUENCY=1m
      #      - SH_ID_PLATFORM_ONCHAIN_CHECK_STATUS_FRECUENCY=1m
      #      - SH_ID_PLATFORM_LOG_LEVEL=-4
      #      - SH_ID_PLATFORM_LOG_MODE=2
      #      - SH_ID_PLATFORM_HTTPBASICAUTH_USER=user
      #      - SH_ID_PLATFORM_HTTPBASICAUTH_PASSWORD=password
      #      - SH_ID_PLATFORM_KEY_STORE_PLUGIN_IDEN3_MOUNT_PATH=iden3
      #      - SH_ID_PLATFORM_REVERSE_HASH_SERVICE_URL=http://localhost:3001
      #      - SH_ID_PLATFORM_REVERSE_HASH_SERVICE_ENABLED=false
      #      - SH_ID_PLATFORM_ETHEREUM_DEFAULT_GAS_LIMIT=600000
      #      - SH_ID_PLATFORM_ETHEREUM_CONFIRMATION_TIME_OUT=600s
      #      - SH_ID_PLATFORM_ETHEREUM_CONFIRMATION_BLOCK_COUNT=5
      #      - SH_ID_PLATFORM_ETHEREUM_RECEIPT_TIMEOUT=600s
      #      - SH_ID_PLATFORM_ETHEREUM_MIN_GAS_PRICE=0
      #      - SH_ID_PLATFORM_ETHEREUM_MAX_GAS_PRICE=1000000
      #      - SH_ID_PLATFORM_ETHEREUM_RPC_RESPONSE_TIMEOUT=5s
      #      - SH_ID_PLATFORM_ETHEREUM_WAIT_RECEIPT_CYCLE_TIME=30s
      #      - SH_ID_PLATFORM_ETHEREUM_WAIT_BLOCK_CYCLE_TIME=30s
      #      - SH_ID_PLATFORM_PROVER_SERVER_URL=http://localhost:8002
      #      - SH_ID_PLATFORM_PROVER_TIMEOUT=600s
      #      - SH_ID_PLATFORM_CIRCUIT_PATH=./pkg/credentials/circuits
    command: sh -c "sleep 4s && ./migrate && ./platform"

  pending_publisher:
    image: sh-id-platform/api:latest
    depends_on:
      - postgres
      - vault
    environment:
      - SH_ID_PLATFORM_DATABASE_URL=postgres://polygonid:polygonid@postgres:5432/platformid?sslmode=disable
      - SH_ID_PLATFORM_KEY_STORE_ADDRESS=http://vault:8200
      - SH_ID_PLATFORM_KEY_STORE_TOKEN=${KEY_STORE_TOKEN}
      - SH_ID_PLATFORM_ETHEREUM_URL=${KALEIDO_NODE_URL}
      - SH_ID_PLATFORM_REDIS_URL=redis://@redis:6380/1
      - SH_ID_PLATFORM_ETHEREUM_CONTRACT_ADDRESS=${STATE_CONTRACT}
    command: sh -c "sleep 4s &&  ./pending_publisher"
