ServerPort = 3001
ServerUrl = "http://localhost:3001"
NativeProofGenerationEnabled = true
PublishingKeyPath = "pbkey"
OnChainCheckStatusFrecuency = "30s"

[Database]
Url="postgres://polygonid:polygonid@postgres:5432/platformid?sslmode=disable"

[Cache]
RedisUrl="redis://@redis:6380/1"

[HTTPBasicAuth]
User = "user"
Password = "password"

[Log]
Level = -4
Mode = 2

[KeyStore]
Address="http://vault:8200/"
Token="hvs.1pzenz8dba3ogukEijLYuc60"
PluginIden3MountPath="iden3"

[ReverseHashService]
URL="http://localhost:3001"
Enabled= false

[Ethereum]
URL="https://u0i45n8v4g:5xtTUBxBD2Suklqhy2t-R4PEgpVqK-lS5gqyepsBhJ8@u0nc4noce4-u0c5qcrhgs-rpc.us0-aws.kaleido.io"
ContractAddress="0x81Fe83278D501457281dbd9d16FB9046E3Ae059d"
DefaultGasLimit=600000
ConfirmationTimeout="600s"
ConfirmationBlockCount=5
ReceiptTimeout="600s"
MinGasPrice=0
MaxGasPrice=1000000
RPCResponseTimeout="5s"
WaitReceiptCycleTime="30s"
WaitBlockCycleTime="30s"

[Prover]
ServerURL="http://localhost:8002"
ResponseTimeout="600s"

[Circuit]
Path="./pkg/credentials/circuits"
